name       : libyubikey
version    : 1.13
release    : 2
source     :
    - https://developers.yubico.com/yubico-c/Releases/libyubikey-1.13.tar.gz : 04edd0eb09cb665a05d808c58e1985f25bb7c5254d2849f36a0658ffc51c3401
license    : BSD-2-Clause
component  : security.library
summary    : YubiKey C low-level library (also known as yubico-c)
description: |
    Low-level C software development kit for the Yubico YubiKey authentication device.
builddeps  :
    - pkgconfig(libusb-1.0)
    - valgrind
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
