name       : libyubikey
version    : 1.13
release    : 1
source     :
    - https://github.com/Yubico/yubico-c/archive/libyubikey-1.13.tar.gz : dd046c83e67560206b0b3301ee8053922b516e3975b895804582eb8d7bdd1d79
license    : BSD
summary    : Low-level C software development kit for the Yubico YubiKey authentication device.
description: |
    Low-level C software development kit for the Yubico YubiKey authentication device.
patterns : 
    - [ /usr/bin, /usr/lib64/*.so*]
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    autoreconf -fi
    rm *.1.txt
    sed -i '51d' configure.ac
    sed -i '66d' Makefile.am
    sed -i '69,73d' Makefile.am
    %configure
build      : |
    %make
install    : |
    %make_install
